### ISSUE TITLE
割り算を実施すると結果が掛け算の結果になる

### ISSUE THREAD

**Issue by colmonti** [colmonti/git-boot-camp-20181130-work1#1]
## 操作手順
* 10 ÷ 2を実施したら
* 答えが20になった

## 本来の想定
* 10÷2を実施したら
* 答えは5になってほしい

## 操作環境
* OS
* OSバージョン
* ブラウザ
* ブラウザバージョン

**Comment by ko333** [comment]
修正を確認しました。
